#ifndef LIBGEODECOMP_TESTBED_REVERSETIMEMIGRATION_CONFIG_H
#define LIBGEODECOMP_TESTBED_REVERSETIMEMIGRATION_CONFIG_H

#define DIM_X 1070
#define DIM_Y 256
#define DIM_Z 512

#define GRID_DIM_X 14
#define GRID_DIM_Y 16
#define BLOCK_DIM_X 64
#define BLOCK_DIM_Y 8


#endif
