#ifndef LIBGEODECOMP_TESTBED_REVERSETIMEMIGRATION_CUDASTEPPERLIB_H
#define LIBGEODECOMP_TESTBED_REVERSETIMEMIGRATION_CUDASTEPPERLIB_H

class CudaStepperLib
{
public:
    void doit(const int& deviceID);
};

#endif

