#include "hpxserialization.h"

HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::Chronometer)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::Coord<1 >)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::Coord<2 >)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::Coord<3 >)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::FloatCoord<1 >)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::FloatCoord<2 >)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::FloatCoord<3 >)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::NonPoDTestCell)
HPX_SERIALIZATION_REGISTER_CLASS(LibGeoDecomp::OozeBalancer)

