#ifndef LIBGEODECOMP_MISC_MATH_H
#define LIBGEODECOMP_MISC_MATH_H

#include <libflatarray/macros.hpp>

LIBFLATARRAY_DISABLE_SYSTEM_HEADER_WARNINGS_PRE
#ifdef _MSC_BUILD
#  ifndef _USE_MATH_DEFINES
#    define _USE_MATH_DEFINES
#  endif
#endif
#include <cmath>
LIBFLATARRAY_DISABLE_SYSTEM_HEADER_WARNINGS_POST

#define LIBGEODECOMP_PI 3.14159265359

#endif
