"// z Koordinate absolut, x und y relativ\n"
"__kernel void execute(\n"
"    __global struct Cell* idata, __global struct Cell* odata,\n"
"    int zDim, int yDim, int xDim, int planes, int offsetZ,\n"
"    int offsetY, int offsetX, __global int* startCoords, __global int* endCoords,\n"
"    int actualX, int actualY)\n"
"{\n"
"    int indexX = get_global_id(0) + offsetX;\n"
"    int indexY = get_global_id(1) + offsetY;\n"
"    //int indexZ = get_global_id(2) * planes + offsetZ;\n"
"    \n"
"    int startStopIndex = get_global_id(2) * actualX * actualY + get_global_id(1) * actualX + get_global_id(0);\n"
"    int minZ = startCoords[startStopIndex];\n"
"    int maxZ = endCoords[startStopIndex];\n"
"    \n"
"    int index = minZ * xDim * yDim + indexY * xDim + indexX;\n"
"    \n"
"    for (; minZ < maxZ; ++minZ) {\n"
"        update(odata + index,\n"
"                idata + index - xDim * yDim,\n"
"                idata + index - xDim,\n"
"                idata + index,\n"
"                idata + index + xDim,\n"
"                idata + index + xDim * yDim);\n"
"        index += xDim * yDim;\n"
"    }\n"
"}\n"
