#!/usr/bin/python
import sys
from subprocess import call

# The purpose of this script is to bundle the generation of the
# scaffolding code for unit tests into one command invocation as CMake
# on Windows struggles with more than one such task per directory
# (i.e. it will only execute one command created via
# add_custom_command(), causing all other test sources in that
# directory not to be created).

arg_index = 1
python = "python"

if sys.argv[1] == "--python":
    python = sys.argv[2]
    arg_index = 3

cxxtestgen = sys.argv[arg_index]
arg_index += 1

for source in sys.argv[arg_index:-1]:
    header = source.replace(".cpp", ".h").replace(".cu", ".h")
    call([python, cxxtestgen, "-o", source, "--part", header])

run_tests_source = sys.argv[-1]
call([python, cxxtestgen, "-o", run_tests_source, "--root", "--main", "run_tests", "--error-printer"])
